SaltToTasteProject/recipes/urls.py
from django.urls import path, include
from .views import *


recipes_urls = [
    path('', search_recipes, name='search'),
    path('collections/', selections, name='collections'),
    path('favorites/', favorites, name='favorites'),
    path('collections/<int:pk>/', CollectionDetailView.as_view(), name='collections-detail'),

    path('collections-detail/', collections_detail, name='collections-detail'),


    path('save_recipe/', SaveRecipeCreateView.as_view(), name='save_recipe'),
    path('save_collection', SaveSelectionCreateView.as_view(), name='save_collection'),
    path('like_comment/', LikeCommentCreateView.as_view(), name='like_comment'),
    path('recipe/<int:pk>/comments/create/', CommentCreateView.as_view(), name='comment_create_view'),
    path('recipe/<int:pk>/', RecipeDetailView.as_view(), name='recipe_detail'),
    # path('recipe/<int:pk>', recipe_detail, name='recipe_detail'),
    path('recipe_add/', add_recipe, name='add_recipe'),
    # path('test_add_recipe/', test_add_recipe, name='add_recipe'),
    path('create_selection/', create_selection, name='create_selection'),
    path('api/ingredients/', IngredientSearchView.as_view(), name='ingredient-search'),
]

urlpatterns = [
    path('', index, name='home'),
    path('search/', include(recipes_urls)),

]

SaltToTasteProject/recipes/forms.py
from django import forms
from .models import CommentRecipe, Recipe, RecipeStep, IngredientQuantity
from django.forms import modelformset_factory

class CommentCreateForm(forms.ModelForm):
    parent = forms.IntegerField(widget=forms.HiddenInput, required=False)
    content = forms.CharField(label='', widget=forms.Textarea(attrs={
        'cols': 30,
        'rows': 5,
        'placeholder': 'Комментарий',
        'class': 'form-control'
    }))

    class Meta:
        model = CommentRecipe
        fields = ('content',)


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'description', 'difficulty', 'cookingTime', 'picture', 'ingredients']


class StepForm(forms.ModelForm):
    class Meta:
        model = RecipeStep
        fields = ['description', 'image']


class IngredientQuantityForm(forms.ModelForm):
    class Meta:
        model = IngredientQuantity
        fields = ['ingredient', 'quantity']

IngredientQuantityFormSet = modelformset_factory(IngredientQuantity, form=IngredientQuantityForm, extra=1)

class RecipeStepForm(forms.ModelForm):
    class Meta:
        model = RecipeStep
        fields = ['description', 'image']

StepFormSet = modelformset_factory(RecipeStep, form=RecipeStepForm, extra=1)

SaltToTasteProject/recipes/templates/recipes/comments_list.html
<!--{% load static %}-->
{% load mptt_tags static mathfilters %}

<div class="recipe__comments">
    {% if request.user.is_authenticated %}
        {% csrf_token %}
        <form method="post" action="{% url 'comment_create_view' recipe.pk %}" id="commentForm" name="commentForm"
            data-recipe-id="{{ recipe.pk }}">
            <textarea name="content" cols="30" rows="10"
                      placeholder="Понравилось? Поделитесь впечатлением" required id="id_content"></textarea>
            <input type="hidden" name="parent" id="id_parent">
            <button class="btn-standart" type="submit" id="commentSubmit">Отправить</button>
        </form>
    {% endif %}
    {% recursetree recipe.comments.all %}
    <ul id="comment-thread-{{ node.pk }}">
        <li>
            <div class="comment__container {% if node.level > 0 %}reply__comment{% endif %}">
                <img src="{{ node.author.avatar.url }}" alt="profile-icon">
                <div class="comment__content">
                    <div class="comment__header">
                        <p class="comment__nickname">@{{ node.author.username }}</p>
                        <p class="comment__date">{{ node.time_create }}</p>
                    </div>
                    <div class="comment__text">
                        <p>{{ node.content }}</p>
                    </div>
                    <div class="comment__functions">
                        <svg width="24" height="24">
                            {% if node.author != user %}
                            <a class="btn-reply" href="#commentForm" data-comment-id="{{ node.pk }}"
                               data-comment-username="{{ node.author }}">
                                <use href="#reply"></use>
                            </a>
                            {%endif%}
                        </svg>
                        <div class="like" data-comment="{{ node.pk }}">
                            <svg width="18" height="18">
                                <use href="{% if like_comments %}{% if node.pk in like_comments %}#like-enable{% else %}#like{% endif %}{% else %}#like{% endif %}"></use>
<!--                                <use href="{% for like in like_comments %}{% if like.comment == node %}#like-enable{% endif %}{% endfor %}"></use>-->
<!--                                <use href="{% for like in like_comments %}{% if like == node %} #like-enable{% else %} #like-enable{% endif %}-->
<!--                                           {% endfor %}"></use>-->

<!--                                <use href="{% if request.user.is_authenticated %}-->
<!--                                                {% if node.author == user %}-->
<!--                                                    #like-enable-->
<!--                                                {%else%}-->
<!--                                                    #like-->
<!--                                                {%endif%}-->
<!--                                            {%else%}-->
<!--                                            #like-->
<!--                                            {%endif%}"></use>-->
                            </svg>
                            <p class="like-count">{{ node.get_username_like }} {{ node.get_sum_likes }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </li>
        {% if not node.is_leaf_node %}
        {{ children }}
        {% endif %}
    </ul>
    {% endrecursetree %}
</div>

SaltToTasteProject/recipes/templates/recipes/recipe_add.html
{% extends 'base_layout.html' %}

{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'css/recipe_add.css' %}">
{% endblock%}
{% block content %}
<form id="recipe-form" enctype="multipart/form-data">
    {% csrf_token %}
    <main class="page__recipe_add">
        <div class="recipe_add__header">
            <a href="#" class="recipe_add__header-link">
                <h1>Добавление рецепта</h1>
                <img src="{% static 'img/svg_image/addreciept.svg' %}" width="30" height="30" alt="Добавить свой рецепт">
            </a>
        </div>
        <div class="recipe_add__container">
            <div class="recipe_add__content">
                <div class="recipe_add__container-add_step">
                    <!--<h4>1. Название блюда</h4>
                    <div class="container-add_content">
                            {{ recipe_form.title }}
                    </div>-->
                    <h4>1. Название рецепта</h4>
                    <div class="container-add_content">
                        <input type="text" id="recipe_name" name="recipe_name" required>
                    </div>
                </div>
            </div>
            <div class="recipe_add__content">
                <div class="recipe_add__container-add_step">
                    <h4>2. Краткое описание</h4>
                    <div class="container-add_content">
                        <textarea id="recipe_description" name="recipe_description" required></textarea>
                        <p style="margin-left: auto; margin-right: 7%; margin-top: 7px; color: rgba(0, 0, 0, 0.70); font-size: 14px;">До 310 символов</p>
                    </div>
                </div>
            </div>
            <div class="recipe_add__content">
                <div class="recipe_add__container-add_step">
                    <h4>3. Загрузите обложку рецепта</h4>
                    <div class="container-add_content">
                        <label class="input-file-label" for="recipe_image">
                            <svg width="128" height="128">
                                <use id="file_add" href="#image_add"></use>
                            </svg>
                            <span id="title_file">Добавить файл</span>
                        </label>
                        <input class="input-file" id="recipe_image" name="recipe_image" type="file" onchange="inputSelected()" accept=".png, .jpg, .jpeg" required/>
                    </div>
                </div>
            </div>
            <div class="recipe_add__content">
                <div class="recipe_add__container-add_step">
                    <h4>4. Ингредиенты</h4>
                    <div class="container-add_content">
                        <input type="text" id="ingredient-search" name="ingredient_search" placeholder=" ">
                        <p class="ingredient__search-title">Быстрый выбор</p>
                        <div class="available-ingredients">
                            {% for ingredient in ingredients %}
                                {% if forloop.counter < 50 %}
                                    <div id="ingredient-buttons"></div>
                                    <button type="button" class="ingredient-button" data-ingredient-id="{{ ingredient.id }}">{{ ingredient.name }}</button>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="ingredients_quantity__container">
                        <div class="ingredient-quantity">
                            <div class="quantity__container" style="margin-bottom: 5px;">
                                <div class="quantity__button"><p>Вы выбрали:</p></div>
                                <div class="quantity__input" style="text-align: center; border: none;"><p>Укажите количество:</p></div>
                            </div>
                        </div>
                        <div class="ingredient-new">
                            <p>Различные специи, пряности и др. Вы можете прописать ниже, они не будут включены в тэги* для расширенного поиска рецепта.
                                <br/> Так же, введите ингредиент, которого не нашлось в нашем списке продуктов.</p>
                            <input type="text" id="add-new__ingredient" name="add-new__ingredient" placeholder="Дополнительные ингредиенты, например “Соль по вкусу”">
                        </div>
                    </div>
                </div>
            </div>
            <div class="recipe_add__content">
                <div class="recipe_add__container-add_step">
                    <h4>5. Шаги приготовления</h4>

                    <div class="container-add_content" id="steps-section">
                        <div class="ingredient__step-list" id="added-steps"></div>
                        <svg width="64" height="64" id="add-step">
                            <use href="#plus-icon"></use>
                        </svg>
                        <span>Добавить шаг</span>
                    </div>
                </div>
            </div>
            <div class="recipe_add__content">
                <div class="recipe_add__container-add_step">
                    <h4>6. Краткая инструкция</h4>
                    <div class="container-add_content">
                        <div class="instructions__btn">
                            <div class="border-bottom"></div>
                            <span class="instructions_steps__btn" id="instructions_steps__btn-id"><p>Собрать из описания <br> шагов приготовления</p></span>
                            <span class="instructions_steps-list-btn" id="instructions_steps-list-btn-id"><p>Написать самостоятельно</p></span>
                            <div class="border-bottom"></div>
                        </div>
                        <div class="instructions_steps">
                            <div class="instruction-summary" id="instruction-summary">
                                <ol class="summary-list" id="summary-list"></ol>
                            </div>
                        </div>
                        <div class="instructions_briefly">
                            <textarea name="" id="" cols="30" rows="10"></textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="recipe_add__content">
                <div class="recipe_add__container-add_step">
                    <h4>7. Оцените сложность и время приготовления</h4>
                    <div class="container-add_content inrow">
                        <div class="difficulty-container">
                                <label for="difficulty">Сложность</label>
                            <select id="difficulty" name="difficulty">
                                <option value="Легко">Легко</option>
                                <option value="Средняя">Средне</option>
                                <option value="Сложно">Сложно</option>
                            </select>
                        </div>
                        <div class="time-container">
                            <label for="cooking_time">Время приготовления</label>
                            <input type="number" name="cooking_time" id="cooking_time" required>
                        </div>
                    </div>
                </div>
            </div>
            <div class="recipe_add__btn">
                <div class="recipe_add__btn-collections">
                    <button type="submit">Сохранить в избранном</button>
                    <p>Рецепт будете видеть только Вы во вкладке «Избранное»</p>
                </div>
                <div class="recipe_add__btn-publish">
                    <button type="submit" id="save-recipe">Опубликовать</button>
                    <p>После модерации Ваш рецепт будет опубликован!</p>
                </div>
            </div>
        </div>
    </main>
</form>
{% endblock %}
{% block script %}
    <script src="{% static 'js/recipe_add.js' %}"></script>
{% endblock %}

SaltToTasteProject/recipes/templates/recipes/recipe_card.html
{% load static %}

<article class="index__article-content">
    <div class="index-article__img">
        <a href="">
            <img class="article__img" src="{{ recipe.picture.url }}" alt="{{ recipe.title }}" />
        </a>
    </div>
    <div class="index-article-section">
        <div class="index-article_content-block">
            <div class="index-article__header">
                <h4>
                    {% if percentsDict|length > 0 %}
                        {% for dict in percentsDict %}
                            {% for key, value in dict.items %}
                                {% if key == recipe %}
                                    Совпадение {{ value }}
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                </h4>
                <h1 class="index-article__title"><a href="{% url 'recipe_detail' recipe.id %}">{{ recipe.title }}</a></h1>

            </div>
            <p class="index-article__text"><a href="">{{ recipe.description }}</a></p>
        </div>
        <ul class="index-article__list">
            <li class="index-article__items">
                <div class="index-article-item1">

                    <a href="#" class="index-item__image">
                        <svg width="32" height="32">
				            <use href="#comment-icon"></use>
                        </svg>
                        <span class="comment-sum">{{ recipe.get_sum_comments }}</span>
                    </a>

                    <button class="save-recipe-button" data-recipe="{{ recipe.id }}">
                            <svg width="32" height="32">
                                <use href="{% if saves %}{% if recipe.id in saves %}#fav_icon-enable{% else %}#fav_icon{% endif %}{% else %}#fav_icon{% endif %}"></use>
                            </svg>
                        <span class="save-sum">{{ recipe.get_sum_save }}</span>
                    </button>

                </div>
            </li>
            <li class="index-article__item2">
                <p class="index-item_ingredients">
                    {% for dict in recipes_ingr %}
                        {% for key, value in dict.items %}
                            {% if key == recipe %}
                                {{ value|join:", " }}
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                </p>
            </li>
        </ul>
    </div>
</article>

SaltToTasteProject/recipes/templates/recipes/recipe_search.html
{% extends 'base_layout.html' %}

{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'css/reciept_search.css' %}">
{% endblock %}

{% block content %}
<main class="page__recipe-search">
    <div class="search__header">
            <div class="search-header__title">
                <h1>Найти рецепт</h1>
            </div>
            <div class="search-header__btn">
                <a href="{% url 'add_recipe' %}" class="search-header__btn-orange">
                    <svg width="22" height="22">
				        <use href="#add_recipe-icon"></use>
                    </svg>
                    <span>Добавить свой рецепт</span>
                </a>
            </div>
    </div>
  <form method="post" action="{% url 'search' %}" id="search-form">
    <!--Поле поиска (верхнее)-->
    <div class="search__form" accept-charset="windows-1251">
        <input type="text" value="" name="title_search" placeholder="Блюдо">
    </div>

    <div class="search-form__btn-clear">
        <h1>Поиск по ингредиентам</h1>
        <button type="submit" id="">Сбросить</button>
    </div>

    <div class="recipe-search__content">
        <!--<div class="advertising"></div>-->
        <div class="search__field" >
            <div class="search-form__container">
                <div class="search__form-content">
                    <div class="search__form-ingredients" action="" method="get" accept-charset="windows-1251">
                        <input type="text" id="ingredient-search" name="ingredient_search" placeholder="Введите название ингридиента">
                    </div>

                    <div class="search-field__choice">
                        <h3>Быстрый выбор</h3>
                                {% csrf_token %}
                        <div class="available-ingredients">
                            {% for ingredient in ingredients %}
                            <div id="ingredient-buttons"></div>
                            <button type="button" class="ingredient-button" data-ingredient-id="{{ ingredient.id }}">{{ ingredient.name }}</button>
                            {% endfor %}
                        </div>
                        <div class="ingredients__container">
                            <div class="ingredients__container-title">
                            <h3>Вы выбрали:</h3>

                            </div>
                            <div class="selected-ingredients"></div>
                            <div class="ingredient__coincidence">
                                <label>
                                <input type="checkbox" id="coincidence" onclick="check();" name="coincidence" autocomplete="off" disabled/>
                                Только 100% совпадение
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="fl_row">
                    <div class="sorting__container">
                        <div class="fl_column">
                            <div class="difficulty-container">
                                <div class="parameters__name-box">
                                    <label for="difficulty">Сложность</label>
                                </div>
                                <select id="difficulty" name="difficulty">
                                    <option value="Все">Все</option>
                                    <option value="Легко">Легкая</option>
                                    <option value="Средняя">Средняя</option>
                                    <option value="Сложно">Сложная</option>
                                </select>
                            </div>
                            <div class="difficulty-container">
                                <div class="parameters__name-box">
                                    <label for="search-sorting">Сортировать по</label>
                                </div>
                                <select id="search-sorting" name="sorting">
                                    <option value="popularity">Популярность</option>
                                    <option value="difficulty">Сложность</option>
                                    <option value="cookingTime">Время приготовления</option>
                                    <option value="Дата публикации">Дата публикации</option>
                                </select>
                            </div>
                        </div>
                        <div class="difficulty-container">
                            <div class="parameters__name-box">
                                <label>Время приготовления</label>
                            </div>
                            <div class="time-container">
                                <p>от</p>
                                <input type="number" maxlength="3" max="200" min="1" name="cooking_time-start" id="cooking_time-start">
                                <p>- до</p>
                                <input type="number" maxlength="3" max="999" min="1" name="cooking_time-end" id="cooking_time-end">
                                <p>мин.</p>
                            </div>
                        </div>
                    </div>
                    <div class="search_bnt-container">
                        <button class="ingredient__coincidence_btn-search" type="submit">Найти</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </form>
            <div class="article-content__title-and-grids">
                <h1>Найдено {{ num_recipes }} совпадений...</h1>
                <div class="article-content__btn-grids" id="sorter">
                    <span class="sorter-item" id="th__btn-3" role="button">
                        <svg width="30" height="30" class="icon-th__btn">
                            <use href="#icon-th"></use>
                        </svg>
                    </span>
                    <span class="sorter-item" id="large__btn-2" role="button">
                        <svg width="30" height="30" class="icon-th-large__btn">
                            <use href="#icon-th-large"></use>
                        </svg>
                    </span>
                    <span class="sorter-item active" id="th-list" role="button">
                        <svg width="30" height="30" class="icon-th-list__btn">
                            <use href="#icon-th-list"></use>
                        </svg>
                    </span>
                </div>
            </div>
            <div class="article-content__container active-1">
            {% for recipe in page_obj %}
                {% include 'recipes/recipe_card.html' %}
            {% endfor %}
            </div>
            {% if page_obj %}
            <div class="pagination">
                {% include 'recipes/paginator.html' %}
<!--                <span class="pagination-btn switch"><</span>-->
<!--                <a href="#" class="pagination-btn active">1</a>-->
<!--                <a href="#" class="pagination-btn">2</a>-->
<!--                <a href="#" class="pagination-btn">3</a>-->
<!--                <span class="pagination-btn&#45;&#45;points">...</span>-->
<!--                <a href="#" class="pagination-btn">20</a>-->
<!--                <span class="pagination-btn switch">></span>-->
            </div>
            {% endif %}
</main>
<script src="{% static 'js/save-comment.js' %}"></script>
{% endblock %}

SaltToTasteProject/recipes/templates/recipes/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{{ recipe_form.title }}

</body>
</html>